<nav class="navbar navbar-expand-sm navbar-light bg-info">
    <div class="container">
          <a href="#" class="navbar-brand">
            <h1>Formulário Envio</h1>
          </a>

          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="/cadastrar" method="post" class="nav-link">Enviar formulário</a>
              </li>
              <li class="nav-item">
                <a href="/informacoes" class="nav-link">Consultar dados</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
